---
server:
  port: 9098
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    dynamic: true
  metadataReport:
    address: zookeeper://127.0.0.1:2181
  configcenter:
    address: zookeeper://127.0.0.1:2181
  application:
    name: yfshop-admin-web
  consumer:
    timeout: 30000
    retries: 0
    check: false
  scan:
    base-packages: com.yfshop.admin.controlle
    
    
spring:
    redis:
        database: 0
        host: 127.0.0.1
        password: ''
        pool:
            max-active: 200
            max-idle: 10
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 1000

logging:
  level:
    org.springframework.web: INFO
    com.yfshop.admin: DEBUG
    me.chanjar.weixin: DEBUG
wx:
  mp:
    useRedis: true
    redisConfig:
      host: 127.0.0.1
      port: 6379
    configs:
      - appId: 1111 # 第一个公众号的appid
        secret: 1111 # 公众号的appsecret
        token: 111 # 接口配置里的Token值
        aesKey: 111 # 接口配置里的EncodingAESKey值

