---
spring:
  application:
    name: yfshop-admin-wx
  profiles:
    active: @profiles.active@
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: true
