---
server:
  port: 9098
dubbo:
  registry:
    address: zookeeper://yf-srv-staging:2181
  metadataReport:
    address: zookeeper://yf-srv-staging:2181
  configcenter:
    address: zookeeper://yf-srv-staging:2181
  application:
    name: yfshop-admin-wx
  consumer:
    timeout: 30000
    retries: 0
    check: false
  scan:
    base-packages: com.yfshop.admin


spring:
  # redis配置
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: yf-sz-redis-staging.redis.rds.aliyuncs.com
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: SZ9v4UrVJKfCCDKUxia
    # 连接超时时间（毫秒）
    timeout: 1000ms
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

logging:
  level:
    org.springframework.web: INFO
    com.yfshop.admin: DEBUG
    me.chanjar.weixin: DEBUG
    com.github.binarywang.wxpay: debug
wx:
  mp:
    useRedis: true
    redisConfig:
      host: yf-sz-redis-staging.redis.rds.aliyuncs.com
      port: 6379
      password: SZ9v4UrVJKfCCDKUxia
    configs:
      - appId: wxfe620617eec2f4b0 # 第一个公众号的appid
        secret: 64a61d9e95094f1e974861b62ec4dce8 # 公众号的appsecret
        token: yufanshop # 接口配置里的Token值
        aesKey: U2ztwhpnvy5SNDiICGloZA0Pgi2WdgDmsO4abHCEtvz # 接口配置里的EncodingAESKey
  pay:
    appId: wxfe620617eec2f4b0
    mchId: 1607782065
    mchKey: F1887D3F9E6EE7A32FE5E76F4AB80D63
    subAppId: #服务商模式下的子商户公众账号ID
    subMchId: #服务商模式下的子商户号
    keyPath: classpath:/static/apiclient_cert.p12

