---
server:
  port: 9094

dubbo:
  registry:
    address: zookeeper://10.11.3.98:2181
    dynamic: true
  metadataReport:
    address: zookeeper://10.11.3.98:2181
  configcenter:
    address: zookeeper://10.11.3.98:2181
  application:
    name: yfshop-admin-web
  consumer:
    timeout: 30000
    retries: 0
    check: false
  scan:
    base-packages: com.yfshop.admin


spring:
  thymeleaf:
    # 页面模板页地址
    prefix: file:///home/www/web-deploy/html/merchant.yufan.51jujibao.com/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,${spring.thymeleaf.prefix}
  mvc:
    static-path-pattern: /**


