---
server:
  port: 9094
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    dynamic: true
  metadataReport:
    address: zookeeper://127.0.0.1:2181
  configcenter:
    address: zookeeper://127.0.0.1:2181
  application:
    name: yfshop-admin-merchant
  consumer:
    timeout: 30000
    retries: 0
    check: false
  scan:
    base-packages: com.yfshop.admin

logging:
  level:
    org.springframework.web: DEBUG
    com.yfshop.admin: DEBUG
    me.chanjar.weixin: DEBUG
    com.github.binarywang.wxpay: DEBUG

wx:
  mp:
    useRedis: false
    redisConfig:
      host: 127.0.0.1
      port: 6379
    configs:
      - appId: wxf4797fe8b12cdf62 # 第一个公众号的appid
        secret: 44f813375f7cf549757b846e0d1e6042 # 公众号的appsecret
        token: yufanshop # 接口配置里的Token值
        aesKey: 111 # 接口配置里的EncodingAESKey
websiteCode:
  url: https://prev-merchant.yufanlook.com/#/MerchantRegisterPrep?websiteCode=