---
server:
  port: 9098
dubbo:
  registry:
    address: zookeeper://${ZOOKEEPER_HOST:192.168.11.197}:${ZOOKEEPER_PORT:2181}
    dynamic: true
  metadataReport:
    address: zookeeper://${ZOOKEEPER_HOST:192.168.11.197}:${ZOOKEEPER_PORT:2181}
  configcenter:
    address: zookeeper://${ZOOKEEPER_HOST:192.168.11.197}:${ZOOKEEPER_PORT:2181}
  application:
    name: yfshop-admin-wx
  consumer:
    timeout: 30000
    retries: 0
    check: false
  scan:
    base-packages: com.yfshop.admin.com.yfshop.open.controller
    
    
spring:
    redis:
        database: 0
        host: ${REDIS_HOST:192.168.11.197}:${REDIS_PORT:6379}
        password: ''
        pool:
            max-active: 200
            max-idle: 10
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 1000

wx:
  mp:
    useRedis: true
    redisConfig:
      host: 127.0.0.1
      port: 6379
    configs:
      - appId: 1111 # 第一个公众号的appid
        secret: 1111 # 公众号的appsecret
        token: 111 # 接口配置里的Token值
        aesKey: 111 # 接口配置里的EncodingAESKey
  pay:
    appId: #微信公众号或者小程序等的appid
    mchId: #微信支付商户号
    mchKey: #微信支付商户密钥
    subAppId: #服务商模式下的子商户公众账号ID
    subMchId: #服务商模式下的子商户号
    keyPath: # p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）