---   
server:
  port: 9091
dubbo:
  registry:
    address: zookeeper://10.10.3.31:2181
    dynamic: true
  metadataReport:
    address: zookeeper://10.10.3.31:2181
  configcenter:
    address: zookeeper://10.10.3.31:2181
  application:
    name: yfshop-shop-web
  consumer:
    timeout: 30000
    retries: 0
    check: false
  scan:
    base-packages: com.yfshop.shop.controller

spring:
  redis:
    database: 0
    host: 127.0.0.1
    password: ''
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1000
