---   
server:
  port: 9090

dubbo:
  registry:
    address: zookeeper://10.11.3.98:2181
    dynamic: true
  metadataReport:
    address: zookeeper://10.11.3.98:2181
  configcenter:
    address: zookeeper://10.11.3.98:2181
  application:
    name: yfshop-shop-web
  consumer:
    timeout: 30000
    retries: 0
    check: false
  scan:
    base-packages: com.yfshop.shop

spring:
  thymeleaf:
    # 页面模板页地址
    prefix: file:///home/www/web-deploy/html/shop.yufan.51jujibao.com/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,${spring.thymeleaf.prefix}
  mvc:
    static-path-pattern: /**
  redis:
    database: 0
    host: yf-sz-redis-staging.redis.rds.aliyuncs.com
    password: redis_staging:SZ9v4UrVJKfCCDKUxia
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
    port: 6379
    timeout: 1000
