---
server:
  port: 9998

dubbo:
  registry:
    address: zookeeper://10.11.3.98:2181
  metadataReport:
    address: zookeeper://10.11.3.98:2181
  configcenter:
    address: zookeeper://10.11.3.98:2181
  protocol:
    port: 20888
    name: dubbo
  scan:
    base-packages: com.yfshop.wx
  provider:
    dynamic: true
    timeout: 30000
    retries: 0
  consumer:
    check: false

logging:
  level:
    org.springframework.web: INFO
    com.yfshop.admin: DEBUG
    me.chanjar.weixin: DEBUG
    com.github.binarywang.wxpay: DEBUG

spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 3
    validationQuery: select 'x'
    initialSize: 1
    maxWait: 60000
    filters: stat,wall,slf4j
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.10.204.28:3306/yf_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: youshenghui
    password: SbaFqsJr4mbt5STZ4Ja
    maxPoolPreparedStatementPerConnectionSize: 20
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 30000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 20

wx:
  mp:
    useRedis: false
    configs:
      - appId: wxf4797fe8b12cdf62 # 第一个公众号的appid
        secret: 44f813375f7cf549757b846e0d1e6042 # 公众号的appsecret
        token: yufanshop # 接口配置里的Token值
        aesKey: U2ztwhpnvy5SNDiICGloZA0Pgi2WdgDmsO4abHCEtvz # 接口配置里的EncodingAESKey
  pay:
    appId: wxfe620617eec2f4b0
    mchId: 1607782065
    mchKey: F1887D3F9E6EE7A32FE5E76F4AB80D63
    subAppId: #服务商模式下的子商户公众账号ID
    subMchId: #服务商模式下的子商户号
    keyPath: /home/www/web-deploy/yufan-admin-wx/cert/apiclient_cert.p12
