---
server:
  port: 9095
logging:
  level:
    com.yfshop.code.mapper: debug
    com.yfshop: debug

spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 3
    validationQuery: select 'x'
    initialSize: 1
    maxWait: 60000
    filters: stat,wall,slf4j
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://prev.mysql.lb.hello.com:3306/yufan_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: jjbJfSaas
    password: onlineJfsaas
    maxPoolPreparedStatementPerConnectionSize: 20
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 30000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 20

  redis:
    host: yf-sz-redis-staging.redis.rds.aliyuncs.com
    port: 6379
    password: SZ9v4UrVJKfCCDKUxia

  mail:
    host: smtp.sina.cn
    port: 465
    username: yflook@sina.cn
    password: 558eac7a98baacf4
    protocol: smtp
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: 雨帆健康家

dubbo:
  registry:
    address: zookeeper://yf-srv-staging:2181
  metadataReport:
    address: zookeeper://yf-srv-staging:2181
  configcenter:
    address: zookeeper://yf-srv-staging:2181
  protocol:
    port: 20882
    name: dubbo
  scan:
    base-packages: com.yfshop.admin
  provider:
    dynamic: true
    timeout: 30000
    retries: 0
  consumer:
    check: false

qiniu:
  domain: qqjyvi051.hn-bkt.clouddn.com
  bucket: yufanshop
  access: DSM_E9p8v4nikrb0W6ovHkzxH_2uRtz8c5-nx8y6
  secret: QFrGQnxFdOzz-iNKQmilWQGdnrzy-3ScVGYGVQG7
  prefix: /yufanshop

xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://yf-srv-staging:8780/xxl-job-admin
      ### xxl-job, access token
    accessToken:
    ### xxl-job executor appname
    executor:
      appname: yufshop-admin-executor-task
      ### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address=:
      ### xxl-job executor server-info
      ip=:
      port: 19999
      ### xxl-job executor log-path
      logpath: /data/applogs/xxl-job/jobhandler
      ### xxl-job executor log-retention-days
      logretentiondays: 30


websiteCode:
  dir: /opt/yufshop/websiteCode/
  url: http://merchant.yufan.51jujibao.com/#/MerchantRegisterPrep?websiteCode=

actCode:
  srcDir: /opt/yufshop/actCode/src/
  targetDir: /opt/yufshop/actCode/target/
  url: http://activity.yufan.51jujibao.com/#/Activity?actCode=

