---
server:
  port: 9093
logging:
  level:
    com.yfshop.code.mapper: debug
    com.yfshop: debug

spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 3
    validationQuery: select 'x'
    initialSize: 1
    maxWait: 60000
    filters: stat,wall,slf4j
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://121.40.70.203/yf_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Wuyc521125!
    maxPoolPreparedStatementPerConnectionSize: 20
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 30000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 20

    redis:
        database: 1
        host: 192.168.11.197
        password: ''
        jedis:
          pool:
            max-active: 200
            max-idle: 10
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 1000
  
  
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  metadataReport:
    address: zookeeper://127.0.0.1:2181
  configcenter:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: 20982
    name: dubbo
  scan:
    base-packages: com.yfshop.shop.service
  provider:
    dynamic: true
    timeout: 30000
    retries: 0
  consumer:
    check: false
wxPay:
  notifyUrl: http://prev-wx.yufan.51jujibao.com/wx/pay/notify/order/

shop:
  url: https://prev-m.yufanlook.com/