---
server:
  port: 10000
spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 3
    validationQuery: select 'x'
    initialSize: 1
    maxWait: 60000
    filters: stat,wall,slf4j
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://prev.mysql.lb.hello.com:3306/yufan_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: jjbJfSaas
    password: onlineJfsaas
    maxPoolPreparedStatementPerConnectionSize: 20
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 30000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 20
  
  
dubbo:
  registry:
    address: zookeeper://yf-srv-staging:2181
  metadataReport:
    address: zookeeper://yf-srv-staging:2181
  configcenter:
    address: zookeeper://yf-srv-staging:2181
  protocol:
    port: 20881
    name: dubbo
  scan:
    base-packages: com.yfshop.open
  provider:
    dynamic: true
    timeout: 30000
    retries: 0
  consumer:
    check: false