---
logging:
  level:
    com.yfshop.code.mapper: debug
    com.yfshop: debug
server:
  port: 10000
spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 3
    validationQuery: select 'x'
    initialSize: 1
    maxWait: 60000
    filters: stat,wall,slf4j
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://yf-rdspro.mysql.rds.aliyuncs.com:3306/db_yf_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: yfshop
    password: 3GqpenFm9GqveeFM4VS
    maxPoolPreparedStatementPerConnectionSize: 20
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 30000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 20
  
  
dubbo:
  registry:
    address: zookeeper://10.11.3.97:2181?backup=10.11.3.99:2181,10.11.3.99:2182
    dynamic: true
  metadataReport:
    address: zookeeper://10.11.3.97:2181?backup=10.11.3.99:2181,10.11.3.99:2182
  configcenter:
    address: zookeeper://10.11.3.97:2181?backup=10.11.3.99:2181,10.11.3.99:2182
  protocol:
    port: 20885
    name: dubbo
  scan:
    base-packages: com.yfshop.open
  provider:
    dynamic: true
    timeout: 30000
    retries: 0