---
server:
  port: 9091

spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 3
    validationQuery: select 'x'
    initialSize: 1
    maxWait: 60000
    filters: stat,wall,slf4j
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://prev.mysql.lb.hello.com:3306/dyf_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: jjbJfSaas
    password: onlineJfsaas
    maxPoolPreparedStatementPerConnectionSize: 20
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 30000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 20
  redis:
    database: 0
    host: yf-sz-redis-staging.redis.rds.aliyuncs.com
    password: SZ9v4UrVJKfCCDKUxia
    pool:
      max-active: 200
      max-idle: 10
      max-wait: -1
      min-idle: 0
    port: 6379
    timeout: 1000

