---   
server:
  port: 9091


spring:
    redis:
        database: 0
        host: 127.0.0.1
        password: ''
        pool:
            max-active: 200
            max-idle: 10
            max-wait: -1
            min-idle: 0
        port: 6379
        timeout: 1000

