---
server:
  port: 9099
dubbo:
  registry:
    address: zookeeper://10.11.3.97:2181?backup=10.11.3.99:2181,10.11.3.99:2182
    dynamic: true
  metadataReport:
    address: zookeeper://10.11.3.97:2181?backup=10.11.3.99:2181,10.11.3.99:2182
  configcenter:
    address: zookeeper://10.11.3.97:2181?backup=10.11.3.99:2181,10.11.3.99:2182
  application:
    name: yfshop-shop-web
  consumer:
    timeout: 30000
    retries: 0
    check: false
  scan:
    base-packages: com.yfshop.open
  provider:
    dynamic: true
    timeout: 30000
    retries: 0

spring:
  thymeleaf:
    # 页面模板页地址
    prefix: file:///home/www/web-deploy/template/yf-open/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html