---
server:
  port: 9099
dubbo:
  registry:
    address: zookeeper://yf-srv-staging:2181
  metadataReport:
    address: zookeeper://yf-srv-staging:2181
  configcenter:
    address: zookeeper://yf-srv-staging:2181
  protocol:
    port: 20951
    name: dubbo
  scan:
    base-packages: com.yfshop.open
  provider:
    dynamic: true
    timeout: 30000
    retries: 0
  consumer:
    check: false