---
server:
  port: 9099
dubbo:
  registry:
    address: zookeeper://10.11.3.98:2181
  metadataReport:
    address: zookeeper://10.11.3.98:2181
  configcenter:
    address: zookeeper://10.11.3.98:2181
  scan:
    base-packages: com.yfshop.open
  provider:
    dynamic: true
    timeout: 30000
    retries: 0
  consumer:
    check: false

spring:
  thymeleaf:
    # 页面模板页地址
    prefix: file:///home/www/web-deploy/template/yf-open/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html