---
server:
  port: 9099
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    dynamic: true
  metadataReport:
    address: zookeeper://127.0.0.1:2181
  configcenter:
    address: zookeeper://127.0.0.1:2181
  application:
    name: yfshop-open-web
  consumer:
    timeout: 30000
    retries: 0
    check: false
    base-packages: com.yfshop.controller

logging:
  level:
    org.springframework.web: DEBUG
    com.yfshop.open: DEBUG
spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB