---
server:
  port: 9096
logging:
  level:
    com.yfshop.code.mapper: debug
    com.yfshop: debug

spring:
  datasource:
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 3
    validationQuery: select 'x'
    initialSize: 1
    maxWait: 60000
    filters: stat,wall,slf4j
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    #    url: jdbc:mysql://10.10.204.28:3306/yf_shop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #    username: youshenghui
    #    password: SbaFqsJr4mbt5STZ4Ja
    url: jdbc:mysql://127.0.0.1:3306/yfshop?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    #    url: jdbc:mysql://10.10.204.28:3306/db_online_jf?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #    username: jjbJfSaas
    #    password: onlineJfsaas
    maxPoolPreparedStatementPerConnectionSize: 20
    testOnBorrow: false
    testWhileIdle: true
    minEvictableIdleTimeMillis: 30000
    timeBetweenEvictionRunsMillis: 60000
    testOnReturn: false
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 20
  redis:
    host: 127.0.0.1
    port: 6379
    password:

  mail:
    host: smtp.126.com
    port: 465
    username: yousheng_hui@126.com
    password: YTLXAVOGNLTZHUBZ
    protocol: smtp
    test-connection: true
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.display.sendmail: 雨帆健康家

dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
  metadataReport:
    address: zookeeper://127.0.0.1:2181
  configcenter:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: 20886
    name: dubbo
  scan:
    base-packages: com.yfshop.admin
  provider:
    dynamic: true
    timeout: 30000
    retries: 0
  consumer:
    check: false

oss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  domain: yf-oss-prev.oss-cn-shenzhen.aliyuncs.com
  bucket: yf-oss-prev
  access: LTAI5tSnQKpNY8rGRDYBH8es
  secret: h9jlsJITV88Yaey82tF9qHSQo9RiiE
  oprefix: /yufan

xxl:
  job:
    admin:
      ### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://192.168.11.197:8780/xxl-job-admin
      ### xxl-job, access token
    accessToken:
    ### xxl-job executor appname
    executor:
      appname: yufshop-admin-report-executor-task
      ### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
      address=:
      ### xxl-job executor server-info
      ip=:
      port: 19998
      ### xxl-job executor log-path
      logpath: /home/www/web-deploy/yufan-admin-report/xxl-job/
      ### xxl-job executor log-retention-days
      logretentiondays: 30


websiteCode:
  dir: F://websiteCode/
  url: https://prev-merchant.yufanlook.com/#/MerchantRegisterPrep?websiteCode=

actCode:
  srcDir: F://actCode/src/
  targetDir: F://actCode/target/
  url: https://prev-m.yufanlook.com/#/LuckDrawPage?actCode=

wxPay:
  notifyUrl: http://prev-wx.yufan.51jujibao.com/wx/pay/notify/order/

shop:
  url: https://prev-m.yufanlook.com/

merchant:
  url: https://prev-merchant.yufanlook.com/