---
server:
  port: 9095

dubbo:
  registry:
    address: zookeeper://10.11.3.98:2181
    dynamic: true
  metadataReport:
    address: zookeeper://10.11.3.98:2181
  configcenter:
    address: zookeeper://10.11.3.98:2181
  application:
    name: yfshop-admin-web
  consumer:
    timeout: 30000
    retries: 0
    check: false
  scan:
    base-packages: com.yfshop.admin

spring:
  thymeleaf:
    # 页面模板页地址
    prefix: file:///home/www/web-deploy/template/yf-admin/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  web:
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,${spring.thymeleaf.prefix}
  mvc:
    static-path-pattern: /**
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  sa-token:
    # 写入Cookie时显式指定的作用域, 用于单点登录二级域名共享Cookie
#    cookie-domain: yufan.51jujibao.com
    # token名称 (同时也是cookie名称)
    token-name: admin
    # token有效期，单位s 默认30天
    timeout: 2592000
    # token风格
    token-style: uuid
    # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
    allow-concurrent-login: true
    token-session-check-login: false
    # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
    activity-timeout: -1
    # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
    is-share: true
oss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  domain: yf-oss-prev.oss-cn-shenzhen.aliyuncs.com
  bucket: yf-oss-prev
  access: LTAI5tR27BbR5u1pmvBtvY8j
  secret: rkqXDsJR4Z98Wdtu4xaIv5gxqaJZ7d
  oprefix: /yufan

  # 文件上传服务器配置
upload:
  server:
    domain: http://c.yufanlook.com
    imagePath: /mnt/static/prev-s.yufanlook.com/image/yf-shop
    excelPath: /mnt/static/prev-s.yufanlook.com/excel/yf-shop