---
server:
  port: 9097
dubbo:
  registry:
    address: zookeeper://yf-srv-staging:2181
    dynamic: true
  metadataReport:
    address: zookeeper://yf-srv-staging:2181
  configcenter:
    address: zookeeper://yf-srv-staging:2181
  application:
    name: yfshop-admin-web
  consumer:
    timeout: 30000
    retries: 0
    check: false
  scan:
    base-packages: com.yfshop.admin

spring:
  redis:
    database: 0
    host: yf-sz-redis-staging.redis.rds.aliyuncs.com
    password: SZ9v4UrVJKfCCDKUxia
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB