---
logging:
  level:
    com.yfshop: debug

server:
  port: 9095
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
    dynamic: true
  metadataReport:
    address: zookeeper://127.0.0.1:2181
  configcenter:
    address: zookeeper://127.0.0.1:2181
  application:
    name: yfshop-admin-web
  consumer:
    timeout: 30000
    retries: 0
    check: false
  scan:
    base-packages: com.yfshop.admin.controller

spring:
    redis:
        database: 0
        host: 127.0.0.1
        password: ''
        port: 6379
        timeout: 1000
        jedis:
          pool:
            max-active: 200
            max-idle: 10
            max-wait: -1
            min-idle: 0
    servlet:
      multipart:
        max-file-size: 100MB
        max-request-size: 100MB

oss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  domain: yf-oss-prev-open.oss-cn-shenzhen.aliyuncs.com
  bucket: yf-oss-prev-open
  access: LTAI5tR27BbR5u1pmvBtvY8j
  secret: rkqXDsJR4Z98Wdtu4xaIv5gxqaJZ7d
  oprefix: /yufan