---
server:
  port: 9097

dubbo:
  registry:
    address: zookeeper://10.11.3.98:2181
    dynamic: true
  metadataReport:
    address: zookeeper://10.11.3.98:2181
  configcenter:
    address: zookeeper://10.11.3.98:2181
  application:
    name: yfshop-admin-web
  consumer:
    timeout: 30000
    retries: 0
    check: false
  scan:
    base-packages: com.yfshop.admin

spring:
  thymeleaf:
    # 页面模板页地址
    prefix: file:///home/www/web-deploy/html/upms.yufan.51jujibao.com/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
    servlet:
      content-type: text/html
  redis:
    database: 0
    host: yf-sz-redis-staging.redis.rds.aliyuncs.com
    password: SZ9v4UrVJKfCCDKUxia
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB